### PR TITLE
Lyapunov fixes

### LINKED ISSUE #94: Change all lyapunov code to use Static Matrices instead of MArray

### LINKED ISSUE #95: Use QR method instead of GM
I don't know why we used GM, but here is the QR method.

Let `W` be a MATRIX with each column the deviation vectors.

You evolve the deviation vectors for *some* time, and then you do:
```julia
LOOP START
Q, R = qr(W)
W = Q
for i in 1:k
    λ[i] += log(abs(R[i,i]))
end
LOOP END

λ ./= LOOP TIME
return λ
```

### PR DESCRIPTION
**Pull request by lhupe**
closes #95 
closes #94

### CODE REVIEW

**Comment by Datseris** [comment]
@lhupe is this ready for review? Can you do me a favor and in the meantime relax the tests of the mean collision time? This is why Travis fails.

File: src/lyapunov_spectrum.jl [hunk 1]
```diff
@@ -31,39 +11,42 @@ together with the components of 4 offset vectors stored in the matrix
...
+
     for k in 1:4
-        x = offset[k]
+        δΓ = offset[k]
         # Formulas from Dellago, Posch and Hoover, PRE 53, 2, 1996: 1485-1501 (eq. 27)
         # with norm(p) = 1
-        a  = x[δpind] - 2.*dot(x[3:4],n)*n + curvature(o)*2./o.r*dot(x[1:2],ti)/cosa*tf
-        b  = x[1:2] - 2.*dot(x[1:2],n)*n
+        δq  = δΓ[δqind] - 2.*dot(δΓ[δqind],n)*n
+        δp  = δΓ[δpind] - 2.*dot(δΓ[δpind],n)*n - curvature(o)*2./o.r*dot(δΓ[δqind],ti)/cosa*tf
```
Comment (Datseris) [inline src/lyapunov_spectrum.jl]: I am guessing this section will be slightly faster with less accesses. You don't actually use `δΓ`. So maybe it is best to start with `δqprev = offset[k][δqind]` and similarly for `δp`.

File: src/lyapunov_spectrum.jl [hunk 2]
```diff
@@ -3,26 +3,6 @@ export lyapunovspectrum!, lyapunovspectrum
 const δqind = SV{Int}(1,2)
 const δpind = SV{Int}(3,4)
```
Comment (Datseris) [inline src/lyapunov_spectrum.jl]: We have to do type-stability checks for this. I think it is fine but it isbest to check!

File: src/lyapunov_spectrum.jl [hunk 3]
```diff
@@ -31,39 +11,42 @@ together with the components of 4 offset vectors stored in the matrix
...
     n = normalvec(o, p.pos)
     specular!(p, o)
     for k in 1:4
-        x = [offset[:,k]...]
+        δΓ = offset[k]
         # Formulas from Dellago, Posch and Hoover, PRE 53, 2, 1996: 1485-1501 (eq. 20)
-        x[1:2]  = x[1:2] -  2.*dot(x[1:2],n)*n
-        x[3:4]  = x[3:4] - 2.*dot(x[3:4],n)*n
+        δq  = δΓ[δqind] -  2.*dot(δΓ[δqind],n)*n
+        δp  = δΓ[δpind] - 2.*dot(δΓ[δpind],n)*n
```
Comment (Datseris) [inline src/lyapunov_spectrum.jl]: Same as with my previous comment on `δΓ`. maybe less accesses are better

File: src/lyapunov_spectrum.jl [hunk 4]
```diff
@@ -72,49 +55,44 @@ end
...
-         # INSTEAD FIND ANALYTICALLY WHAT DOES J*x does for a general x
 
     for k in 1:4
-        Γ = offset[k]
-        offset[k] = SV{T}(whatever you get)
+        δΓ = offset[k]
+        offset[k] = SVector{4,T}(δΓ[1] + sω/ω*δΓ[3] + (cω - 1)/ω*δΓ[4],
+                                 δΓ[2] + (1 - cω)/ω*δΓ[3] + sω/ω*δΓ[4],
+                                 cω*δΓ[3] - sω*δΓ[4],
+                                 sω*δΓ[3] + cω*δΓ[4])
```
Comment (Datseris) [inline src/lyapunov_spectrum.jl]: Exactly!

File: src/lyapunov_spectrum.jl [hunk 5]
```diff
@@ -154,14 +132,16 @@ for a given particle in a billiard table.
 """
 function lyapunovspectrum!(p::AbstractParticle{T}, bt::Billiard{T}, t::T) where {T<:AbstractFloat}
```
Comment (Datseris) [inline src/lyapunov_spectrum.jl]: Can you add a conversion that makes `t` of type `T`, so that this restriction is not present in the call signature?
